// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQa6-5Wy26HTsdVgvljwpD5KnoY2I9Hys',
    appId: '1:469227179625:web:8c42ae7a8fbf27817edcf8',
    messagingSenderId: '469227179625',
    projectId: 'constropedia-7d7a3',
    authDomain: 'constropedia-7d7a3.firebaseapp.com',
    storageBucket: 'constropedia-7d7a3.firebasestorage.app',
    measurementId: 'G-15V6NJ7WVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZtBH7S_ImS4-c-aE_TN2ncovBPqSyNI',
    appId: '1:469227179625:android:e043dfc90582e6667edcf8',
    messagingSenderId: '469227179625',
    projectId: 'constropedia-7d7a3',
    storageBucket: 'constropedia-7d7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8TiSToA30vALW_EmsY2SQBD_RbU_lPBs',
    appId: '1:469227179625:ios:9f867fe12c3665587edcf8',
    messagingSenderId: '469227179625',
    projectId: 'constropedia-7d7a3',
    storageBucket: 'constropedia-7d7a3.firebasestorage.app',
    iosBundleId: 'com.example.constropedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8TiSToA30vALW_EmsY2SQBD_RbU_lPBs',
    appId: '1:469227179625:ios:9f867fe12c3665587edcf8',
    messagingSenderId: '469227179625',
    projectId: 'constropedia-7d7a3',
    storageBucket: 'constropedia-7d7a3.firebasestorage.app',
    iosBundleId: 'com.example.constropedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQa6-5Wy26HTsdVgvljwpD5KnoY2I9Hys',
    appId: '1:469227179625:web:9ddd63faffce56367edcf8',
    messagingSenderId: '469227179625',
    projectId: 'constropedia-7d7a3',
    authDomain: 'constropedia-7d7a3.firebaseapp.com',
    storageBucket: 'constropedia-7d7a3.firebasestorage.app',
    measurementId: 'G-370KGT1XM7',
  );
}
